# This is information about infrastructure, systems and available equipment that has a static nature and 
# may differ between different sites. 
# It is a way to simplify and homogenize the definition of components and their deployments.
#
# All first level variables SHOULD start by the prefix site_
#
# SITE: UMA
#

site_hypervisor: one #one, vmware, etc ...
site_default_network_id: 0
site_networks:
  - name: External Network   # Representative Name
    id: 0                    # ID from OpenNebula Networks List
    if_name: br_281_srv      # Interface that support this Network
  - name: NTN Network
    id: 13
    if_name: br_120
site_vxlan_if: br_281_srv     # It must be the name of the interface on which the new vxlan will be created
site_network_clusters: [0, 100, 101, 102]

site_s3_server:
  endpoint: "http://10.11.28.95:9000"
  bucket: "trial-networks"
  region: "main"
  skip_requesting_account_id: "true"
  skip_credentials_validation: "true"
  skip_metadata_api_check: "true"
  skip_region_validation: "true"
  force_path_style: "true"

site_one_templates:
  tn_bastion:
    id: 41
  vm_xs:
    id: 42 

site_jenkins_ssh_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCCweY1fDXtrxltSW36ln2Ktk8V0E6TDfqsjEBfW6gAqco2k5BnosCVVm7kWCYOmvYa94e1yMA/j9H037TQBiUu9iQHjxaxR4rs/1plH3XyIYItPWdwKft22QrQBUBlLUcrCdII/adpdFnPzZux5xU34Ytm7XjSAikVlwv4TIYcWC3J9TGvmA4YaoIwcgJEwtaGCuUhkjn03CLx3YB++0bGnsicpw8fi0EGOfoNvRexGRXAE/Ogad+8RF3mWyVl+CYhcdbEOcNfdbp9XyZY9WT8yyimzSlp3gADmA5e5gnlXUjnpiHlrjVrqLt2JOc7QD5pjO92IPR6M9XC6Sz+piG255+FrVBK5KaPcQi6Lo3BGl1sbWFte/UM/TvIRLhJGYEZjpaqn6g+Bh99votEs7a+L7J+YeR3qCLnmaUPIXNue4yz/zJpEQ5Aj+RFybybinK5SV8pUG+H6blJa3TZPD4em7sZ0HLg/VyHiILiIndCuylem0HpcgcI8h/vWSw+syU= jenkins"
site_jenkins_script_base64: "IyEvYmluL2Jhc2gKc3NoLWtleWdlbiAtdCByc2EgLU4gIiIgLWYgfi8uc3NoL2lkX3JzYQplY2hvIFBhc3N3b3JkQXV0aGVudGljYXRpb24geWVzID4gL2V0Yy9zc2gvc3NoZF9jb25maWcuZC9QYXNzd29yZEF1dGhlbnRpY2F0aW9uLmNvbmYKZWNobyAic3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCZ1FDQ3dlWTFmRFh0cnhsdFNXMzZsbjJLdGs4VjBFNlREZnFzakVCZlc2Z0FxY28yazVCbm9zQ1ZWbTdrV0NZT212WWE5NGUxeU1BL2o5SDAzN1RRQmlVdTlpUUhqeGF4UjRycy8xcGxIM1h5SVlJdFBXZHdLZnQyMlFyUUJVQmxMVWNyQ2RJSS9hZHBkRm5Qelp1eDV4VTM0WXRtN1hqU0Fpa1Zsd3Y0VElZY1dDM0o5VEd2bUE0WWFvSXdjZ0pFd3RhR0N1VWhram4wM0NMeDNZQisrMGJHbnNpY3B3OGZpMEVHT2ZvTnZSZXhHUlhBRS9PZ2FkKzhSRjNtV3lWbCtDWWhjZGJFT2NOZmRicDlYeVpZOVdUOHl5aW16U2xwM2dBRG1BNWU1Z25sWFVqbnBpSGxyalZycUx0MkpPYzdRRDVwak85MklQUjZNOVhDNlN6K3BpRzI1NStGclZCSzVLYVBjUWk2TG8zQkdsMXNiV0Z0ZS9VTS9UdklSTGhKR1lFWmpwYXFuNmcrQmg5OXZvdEVzN2ErTDdKK1llUjNxQ0xubWFVUElYTnVlNHl6L3pKcEVRNUFqK1JGeWJ5YmluSzVTVjhwVUcrSDZibEphM1RaUEQ0ZW03c1owSExnL1Z5SGlJTGlJbmRDdXlsZW0wSHBjZ2NJOGgvdldTdytzeVU9IGplbmtpbnMiID4+IC9yb290Ly5zc2gvYXV0aG9yaXplZF9rZXlzCnN5c3RlbWN0bCByZXN0YXJ0IHNzaGQK"
site_one_bastion_default_password: "UMAoperator"